GET http://localhost:3000/players/

### 

POST http://localhost:3000/players/
Content-Type: application/json 

{
  "playerName": "Vishal",
  "jerseyNumber": 18,
  "role": "Bowler"
}

###

GET http://localhost:3000/players/4/ 

###

PUT http://localhost:3000/players/4/
Content-Type: application/json

{
  "playerName": "Dhoni",
  "jerseyNumber": 7,
  "role": "Batsman"
}

###

DELETE http://localhost:3000/players/3/



